<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <KnownILCompilerPack Update="Microsoft.DotNet.ILCompiler">
      <ILCompilerPackVersion>11.0.0-dev</ILCompilerPackVersion>
    </KnownILCompilerPack>
    <KnownRuntimePack Update="Microsoft.NETCore.App">
      <LatestRuntimeFrameworkVersion>11.0.0-dev</LatestRuntimeFrameworkVersion>
    </KnownRuntimePack>
    <KnownILLinkPack Update="Microsoft.NET.ILLink.Tasks">
      <ILLinkPackVersion>11.0.0-dev</ILLinkPackVersion>
    </KnownILLinkPack>
  </ItemGroup>
</Project>
